services:
  - type: web
    name: invoice-checker
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: MJ_APIKEY_PUBLIC
        sync: false
      - key: MJ_APIKEY_PRIVATE
        sync: false
      - key: INTERNAL_API_KEY
        sync: false
